### ISSUE TITLE
Data set issues

### ISSUE THREAD

**Issue by yzlucky7** [SdeRodaHusman/remotesensing-of-river-ice#1]
Hello! I am a student studying river ice, I would like to learn your code but during the runtime, the dataset containing the lon and lat columns is missing, do you have that dataset available?

**Comment by SdeRodaHusman** [comment]
Dear @yzlucky7, 

Thanks for your message!

Unfortunately, I am not able to locate the lon/lat dataset. I apologize! It has been a while since I worked on this project (this was work from my MSc thesis in 2020), and I don't longer have the company laptop I worked on during that time. 

If I can assist with anything else, please let me know.

All the best,
Sophie

**Comment by yzlucky7** [comment]
Dear @SdeRodaHusman,
Thank you for the reply to your last question, at the moment I have another question, is there any version information of the environment and dependencies to run this model, I don't know at the moment which version to use to get the model running properly.
Looking forward to your reply, good luck!
WYZ

**Comment by SdeRodaHusman** [comment]
Dear @yzlucky7,

Unfortunately, since I no longer have access to the company laptop I used during my MSc thesis, the files stored here on GitHub are all that I have available. I am very sorry for the inconvenience!

All the best,  
Sophie
